
name: Test

on:
  workflow_dispatch

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - uses: MandalAutomations/Removed_Skipped_Runs@main
        with:
          repo: ${{ github.repository }}
          num_to_delete: 3
          github_token: ${{ github.token }}