
name: Test

on:
  workflow_dispatch

jobs:
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: MandalAutomations/Removed_Skipped_Runs
        uses: MandalAutomations/Removed_Skipped_Runs@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          repo: ${{ github.repository }}
          num_to_delete: 3
